config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  resources :dashboard, only: [:index]
  resources :users, only: %i[edit update]
  resources :sessions, only: %i[create destroy]
  resources :trips, only: %i[index create show new destroy]
  get '/trips/:id/beers', to: 'beers#index'
  resources :beers, only: %i[index show]
  get '/*something' => 'application#not_found'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :full_name, presence: true
  validates :email, presence: true # , uniqueness: true
  validates :uid, presence: true
  validates :avatar_url, presence: true

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.full_name = auth.info.name
      user.email = auth.info.email
      user.uid = auth.uid
      user.avatar_url = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :authorized

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorized
    not_found unless current_user
  end

  def not_found
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @trip_id = params[:trip_id]
    if params[:search].present?
      @beers = BeerFacade.search_beer(params[:search])

    elsif @trip_id.present?
      @beers = BeerFacade.get_beers_data(@trip_id)
    end
  end

  def show; end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @weather = WeatherFacade.get_forecast(current_user.zip_code)
    if @weather.is_a? String
      redirect_to edit_user_path(current_user)
      flash[:error] = @weather
    end
    @beer_of_the_day = BeerFacade.search_beer('').sample
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: :omniauth

  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    if @user.zip_code.present?
      redirect_to dashboard_index_path
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
    flash[:success] = 'You have successfully logged out'
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = TripFacade.see_trip_index(current_user.id)
  end

  def show
    if TripsService.get_trip_show(params[:id])[:id].nil?
      redirect_to '/trips'
      flash[:error] = 'Trip not found'
    elsif params[:beer_id].present?
      TripFacade.new_trip_beer(params[:id], params[:beer_id])
      @trip = TripFacade.get_single_trip(params[:id])
      @beers = @trip.beers
    else
      @trip = TripFacade.get_single_trip(params[:id])
      @beers = @trip.beers
    end
  end

  def new; end

  def create
    new_trip = TripFacade.new_trip(trip_params)
    if new_trip.is_a? Hash
      flash[:error] = new_trip[:errors]
      render :new
    else
      redirect_to beers_path(params: { trip_id: new_trip.id })
    end
  end

  private

  def trip_params
    params.permit(:user_id, :name, :location, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to dashboard_index_path
  end

  private

  def user_params
    params.require(:user).permit(:zip_code)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorized

  def index
    redirect_to dashboard_index_path if current_user.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/index.html.erb
<div id="beers-index">
  <h1> Beers </h1>

  <% if @beers.is_a? String %>
  <h2><%= @beers %></h2>
  <% else %>
  <table>
    <tr>
      <th>Beer</th>
      <th>Style</th>
      <th>ABV</th>
    </tr>
    <% @beers.each do |beer| %>
    <section id="beer-<%=beer.id%>">
      <tr id='tdata'>
        <td><%= beer.name %></td>
        <td><%= beer.style %></td>
        <td><%= beer.abv %>%</td>
        <% if @trip_id.present? %>
        <td><%= button_to 'Add beer to trip!', trip_path(@trip_id), method: :get, params: {beer_id: beer.id} %></td>
        <% end %>
      </tr>
    </section>
    <tr>
      <td id='tdesc' colspan="3"><%= beer.description if beer.description.present? %>
        <%= 'No description Available' if beer.description.empty? %></td>
    </tr>
    <% end %>
  </table>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="page-box">
  <br>
  <h1>Welcome <%= tag.span current_user.full_name + '!', class: 'user-details' %></h1>
  <br>
  <% location = @weather.first %>
  <h2>Three Day Forecast for <%= tag.span "#{location.location_name}, #{location.location_state}", class: 'user-details' %> </h2>
  <section class="weather-forecast">
    <% @weather.each do |day| %>
    <div class="oneforecast">
      <section id="forecast-<%=@weather.find_index(day)%>">
        <p><%= day.date %></p>
        <%= image_tag day.icon %>
        <p> Low: <%= tag.span "#{day.min_temp}˚F", class: 'lo' %> |  High: <%= tag.span "#{day.max_temp}˚F", class: 'hi' %> </p>
        <p><%= day.description %></p>
      </section>
    </div>
    <% end %>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>DowndraftFrontend</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>

  </div>
</head>

<body>
  <% if current_user.present? && action_name != 'not_found' %>
  <input type="checkbox" id="active">
  <label for="active" class="menu-btn"><i class="fas fa-bars"></i></label>
  <div class="searchbar-container">
    <div class="searchbar">
      <%= form_with url: beers_path, method: :get do |f| %>
      <%= f.text_field :search, class:"searchbar-input", placeholder: "Search for beer by name", required: true, size: 30 %>
      <%= f.submit "Search", class:"searchbar-button" %>
      <% end %>
    </div>
  </div>
  <div class="wrapper">
    <ul>
      <li><%= image_tag current_user.avatar_url, class: 'user-img' %></li>
      <li><%=link_to "Home", dashboard_index_path%></li>
      <li><%=link_to "New Trip", new_trip_path%></li>
      <li><%=link_to "Scheduled Trips", trips_path%></li>
      <li><%= link_to 'Logout', session_path(session), method: :delete %></li>
    </ul>
  </div>
  <% end %>

  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
  <% end %>
  <%= yield %>
  <div id="footer">
    <%= image_tag('logo.png')%>
  </div>
</body>

</html>

app/views/trips/index.html.erb
<h1>Trips for <%= current_user.full_name %></h1>
<ul id="trip-list">
  <% @trips.each do |trip| %>
  <li id="trip-<%= trip.id %>" class="trip-details">
    Name: <%= link_to "#{trip.name}", "/trips/#{trip.id}" %> |
    Location: <%= trip.location %> |
    Date: <%= trip.date %> |
    Elevation: <%= trip.elevation %> ft. |
    Max Temperature: <%= trip.max_temp %>˚F<br>
    <% end %>
  </li>
</ul>

app/views/trips/new.html.erb
<div class="new-trip">
  <h1> New Trip</h1>

  <div class="trip-form">
    <%=form_with url: trips_path, method: :post do |f|%>
      <%=f.hidden_field :user_id, value: current_user.id%>
      <span class="form_tag"><%=f.text_field :name, placeholder: "Enter a name for your trip", required: true, size: 30%></span>
      <span class="form_tag"><%=f.text_field :location, placeholder: "Five digit zipcode", required: true, minlength: 5, maxlength: 5, size: 30%></span>
      <span class="form_tag"><%=f.date_field :date, required: true, min: Time.now, max: 10.days.from_now %></span>
      <span class="form_tag"><%= f.submit "Lets Go!", class: 'form-submit' %></span>
    <%end%>
  </div>
</div>

app/views/trips/show.html.erb
<div id="one-trip-page">
  <h1><%= @trip.name %></h1>

  <div class="one-trip">
    Zip Code: <%= @trip.location %><br>
    Date: <%= @trip.date %><br>
    Elevation: <%= @trip.elevation %> ft.<br>
    Max Temp: <%= @trip.max_temp %>˚F
    <br><br>
    <% if @beers.nil? %>
    <p>There are no beers for this trip</p>
    <% else %>
    <div class="trip-beers">
      <%@beers.each do |beer| %>
      <p>Beer: <%=beer.name%></p>
      <p>Style: <%=beer.style%></p>
      <p>ABV: <%=beer.abv%>%</p>
      <%end%>
    </div>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h3>Welcome to DownDraft <%= @user.full_name %>! To get started, please enter your zip code below.</h3>
<%= form_with model: @user do |f| %>
<%= f.text_field :zip_code, minlength: 5, maxlength: 5 %>
<%= f.submit "Submit"%>
<% end %>

app/views/welcome/index.html.erb
<div id='welcome-page'>
  <h1>Welcome to DownDraft</h1>
  <br>
  <h3>Meet the perfect beer for your next adventure. DownDraft recommends beer based on your destination's forecast and elevation.</h3>
  <br>
  <section class='google'>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
    <div class="google-btn">
      <a data-method="post" href="/auth/google_oauth2">
        <div class="google-icon-wrapper">
          <img class="google-icon" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg" />
        </div>
        <p class="btn-text"><b>Sign in with Google</b></p>
      </a>
    </div>
  </section>
  <br>
</div>